Update AWS Private Link security group port guide
redpanda-data/cloud-docs pull request #137
Opened 2024-11-25 15:24 UTC by simonlord

2024-11-25 16:57 UTC, asimms41 commented on modules/networking/pages/aws-privatelink.adoc
> +#   There are 3 ranges that alternate during normal system maintenance and all 3 must be open
```suggestion
#   There are three port ranges that alternate during normal system maintenance, and all three must be open. Adjust the end port number if the Redpanda broker count is not three.
```

2024-11-25 16:59 UTC, asimms41 requested changes
Hi Simon, Looks good. Just a couple of suggestions.

2024-11-25 17:10 UTC, simonlord commented
@asimms41 I accepted your changes, thanks. Ready for review again

2024-11-25 17:12 UTC, paulzhang97 approved these changes

2024-11-25 17:40 UTC, asimms41 commented on modules/networking/pages/aws-privatelink.adoc
> +#   There are three broker port ranges that alternate during normal system maintenance, and all three must be open.  Adjust the end port number if the Redpanda broker count is not three.
```suggestion
#   There are three broker port ranges that alternate during normal system maintenance, and all three must be open. Adjust the end port number if the Redpanda broker count is not three.
```

2024-11-25 17:42 UTC, asimms41 requested changes
Just one very small change then good to go.

2024-11-25 17:57 UTC, simonlord commented
@asimms41 I accepted your change, thanks. Ready for review again

2024-11-26 08:52 UTC, asimms41 approved these changes
LGTM

2024-11-26 09:49 UTC, merged