DOC-745 Serverless Pro
redpanda-data/cloud-docs pull request #158
Opened 2024-12-17 20:18 UTC by micheleRP

## Description

Resolves https://redpandadata.atlassian.net/browse/DOC-745
Review deadline: Jan 7

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2025-01-09 15:29 UTC, simon0191 commented on modules/billing/pages/billing.adoc
> +Serverless pricing depends on the time the instance is up (for Serverless Pro clusters only), the data in, data out, data stored, and partitions (virtual streams).
wdyt about:

Serverless pricing depends on the data in, data out, data stored, partitions (virtual streams), and, for Serverless Pro clusters only, the time the instance is up.

2025-01-09 15:29 UTC, simon0191 commented on modules/billing/pages/billing.adoc
> +| Instance | This tracks the number of hours the instance is running.
This metric is called `uptime`

2025-01-09 15:29 UTC, simon0191 commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
We also have a limit of 200 topics for pro and 20 topics for standard.

2025-01-09 15:29 UTC, simon0191 commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
Let's also mention connect here

2025-01-09 17:12 UTC, micheleRP commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
@simon0191 Please see https://github.com/redpanda-data/documentation-private/issues/2814. Should we document Serverless Standard topic limit as 20 or 30?
cc @jason-da-redpanda

2025-01-09 17:58 UTC, micheleRP commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
Thanks for the confirmation. I updated as 200 for Pro and 20 for Standard.

2025-01-09 18:00 UTC, micheleRP commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
@simon0191 Is Redpanda Connect considered beta for Serverless Pro, similar to Serverless Standard?

2025-01-09 22:15 UTC, kbatuigas reviewed
Just a few clarifying questions for now, but it looks good overall!

2025-01-09 22:15 UTC, kbatuigas commented on modules/get-started/pages/cloud-overview.adoc
> +NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC or VNet, including subnetworks, IAM roles, and storage buckets/accounts. A Bring Your Own Virtual Priv
If we're shifting to "BYOVPC" should we make that update to replace "customer-managed VPC" in the rest of the docs?

2025-01-09 22:15 UTC, kbatuigas commented on modules/get-started/pages/cloud-overview.adoc
> +You can also subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] to quickly provision Serverless clusters. New subscriptions receive $300 (USD) in free credits to
If you don't use up the $300 within the first 30 days do the unused credits roll over? And if it's a subscription through AWS Marketplace it's different from a "trial" that "expires" after a period of time, right? It'll just continue to be active unless you cancel?

2025-01-09 22:44 UTC, simon0191 commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
yeah, it works exactly the same for both

2025-01-09 22:45 UTC, simon0191 approved these changes
LGTM

2025-01-09 22:54 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC or VNet, including subnetworks, IAM roles, and storage buckets/accounts. A Bring Your Own Virtual Priv
Did you see it somewhere? I believe it was already changed everywhere already.

2025-01-09 23:24 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +Serverless Standard is the fastest and easiest way to start data streaming. With Serverless clusters, you host your data in Redpanda's VPC, and Redpanda handles automatic scaling, provisioning, opera
thanks Kat, I've fixed the wording in the table!

2025-01-09 23:26 UTC, micheleRP commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +
Thanks Simon: I added to both Standard and Pro: https://deploy-preview-158--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless-pro/#supported-features

2025-01-09 23:26 UTC, kbatuigas commented on modules/get-started/pages/cloud-overview.adoc
> +NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC or VNet, including subnetworks, IAM roles, and storage buckets/accounts. A Bring Your Own Virtual Priv
Hm, I just get a few hits - RRR (which I may have to update anyway pending the info I get [here](https://github.com/redpanda-data/docs/pull/942/files#r1909251144)), the Terraform provider doc, the RPCN quickstart, and the PSC docs.

2025-01-09 23:28 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +You can also subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] to quickly provision Serverless clusters. New subscriptions receive $300 (USD) in free credits to
Correct, it's not a trial, and yes I believe remaining credits roll into your account if you add a credit card. @towfiqa please correct me if I'm wrong!

2025-01-09 23:34 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC or VNet, including subnetworks, IAM roles, and storage buckets/accounts. A Bring Your Own Virtual Priv
Ah, thanks Kat! Angela's updating the RPCN already for that, but I'll edit the Terraform provider and PSC docs to use BYOVPC in this PR.

2025-01-10 16:33 UTC, kbatuigas requested changes
Just on typo to fix!

2025-01-10 16:33 UTC, kbatuigas commented on modules/get-started/pages/cloud-overview.adoc
> +Serverless Pro is similar to Serverless Standards, but it provides higher usage limits and dedicated support.
```suggestion
Serverless Pro is similar to Serverless Standard, but it provides higher usage limits and dedicated support. 
```

2025-01-10 17:44 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +Serverless Pro is similar to Serverless Standards, but it provides higher usage limits and dedicated support.
updated, thank you!

2025-01-10 18:14 UTC, micheleRP commented on modules/billing/pages/billing.adoc
>  == Serverless metrics
@alenkacz @towfiqa Should we be including a metric for RPCN?

2025-01-10 19:06 UTC, kbatuigas approved these changes

2025-01-14 05:53 UTC, towfiqa requested changes

2025-01-14 05:53 UTC, towfiqa commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +Subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Serverless Standard, Serverless Pro, and Dedicated clusters. With a usage-based pay-as-you-go subscription, you only pay for w
I didn't think this was being supported. Will check with eng and report back

2025-01-14 05:53 UTC, towfiqa commented on modules/billing/pages/billing.adoc
>  == Serverless metrics
Brian does have this in his slides. So I say yes

2025-01-14 05:53 UTC, towfiqa commented on modules/billing/pages/billing.adoc
> +Pricing for Serverless clusters depends on the data in, data out, data stored, partitions (virtual streams), and for Serverless Pro clusters only, the time the instance is up.
Might be simpler to say uptime here

2025-01-14 05:53 UTC, towfiqa commented on modules/get-started/pages/cloud-overview.adoc
> +To start using Serverless Pro, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^]. With this sign up, you get immediate access to dedicated support.
This paragraph is confusing. The sign up is a contact sales so it's not really a sign up. So there is no dedicated support that happens

2025-01-14 05:53 UTC, towfiqa commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +To start using Serverless Pro, subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace]. New subscriptions receive $300 (USD) in free credits to spend in the first 30
Again, not sure we said this was supported

2025-01-14 05:53 UTC, towfiqa commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +. In the https://cloud.redpanda.com[Redpanda Cloud UI^], on the **Clusters** page, click **Create cluster**, then click **Create Serverless Pro cluster**.
Should we mention that someone at RP will create a cloud org and give them access. They will receive welcome email and then these steps happen

2025-01-14 10:50 UTC, simon0191 commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +Subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Serverless Standard, Serverless Pro, and Dedicated clusters. With a usage-based pay-as-you-go subscription, you only pay for w
This is correct. self service AWS marketplace users will have access to serverless pro

2025-01-14 10:51 UTC, simon0191 commented on modules/get-started/pages/cluster-types/serverless-pro.adoc
> +To start using Serverless Pro, subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace]. New subscriptions receive $300 (USD) in free credits to spend in the first 30
It's supported

2025-01-14 15:42 UTC, towfiqa approved these changes

2025-01-14 16:21 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +To start using Serverless Pro, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^]. With this sign up, you get immediate access to dedicated support.
reworded this

2025-01-14 16:47 UTC, merged