2540 - Scaling pipelines in Redpanda Connect
redpanda-data/cloud-docs pull request #57
Opened 2024-09-11 10:43 UTC by asimms41

## Description

Resolves https://github.com/redpanda-data/documentation-private/issues/2540
Review deadline:

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-09-11 11:12 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +----
This example is untested.

2024-09-11 13:30 UTC, bojand commented
Here is a sample work flow. I am using [curlie](https://github.com/rs/curlie) which has similar interface as https://httpie.io/, but I think converting this to curl should be relatively easy. 

Create a pipeline in Cloud Console UX.

That pipeline gets default resources: `1` cpu and `"400M"` for memory.

Then we can list the pipelines:

```sh
❯ http -H "Authorization: Bearer $API_TOKEN" https://api-72db851f.crgdbnhrj9d68idqn1pg.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines
HTTP/2 200
date: Wed, 11 Sep 2024 00:43:52 GMT
content-type: application/json
content-length: 939
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "pipelines": [
        {
            "id": "crgeehphenn8vueg2qog",
            "display_name": "test0",
            "description": "",
            "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-72db851f.crgdbnhrj9d68idqn1pg.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
            "resources": {
                "memory_shares": "400M",
                "cpu_shares": "1"
            },
            "state": "STATE_RUNNING"
        }
    ],
    "next_page_token": ""
}
```

Update the resources and other properties:

```sh
~
❯ cat ~/Downloads/putpipeline.json
{
    "display_name": "test0",
    "description": "update test0",
    "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-e4678888.crg55ilmt9ekcciva6k0.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
    "resources": {
        "memory_shares": "500M",
        "cpu_shares": "0.8"
    }
}

~
❯ http PUT -H "Authorization: Bearer $API_TOKEN" https://api-72db851f.crgdbnhrj9d68idqn1pg.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines/crgeehphenn8vueg2qog < ~/Downloads/putpipeline.json
HTTP/2 200
date: Wed, 11 Sep 2024 00:47:09 GMT
content-type: application/json
content-length: 915
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "id": "crgeehphenn8vueg2qog",
    "display_name": "test0",
    "description": "update test0",
    "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-e4678888.crg55ilmt9ekcciva6k0.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
    "resources": {
        "memory_shares": "500M",
        "cpu_shares": "800m"
    },
    "state": "STATE_RUNNING"
}
```

list the pipelines again to verify:

```sh
~
❯ http -H "Authorization: Bearer $API_TOKEN" https://api-72db851f.crgdbnhrj9d68idqn1pg.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines
HTTP/2 200
date: Wed, 11 Sep 2024 00:47:24 GMT
content-type: application/json
content-length: 952
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "pipelines": [
        {
            "id": "crgeehphenn8vueg2qog",
            "display_name": "test0",
            "description": "update test0",
            "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-e4678888.crg55ilmt9ekcciva6k0.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
            "resources": {
                "memory_shares": "500M",
                "cpu_shares": "800m"
            },
            "state": "STATE_RUNNING"
        }
    ],
    "next_page_token": ""
}
```

2024-09-11 15:10 UTC, bojand commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +By default, every data pipeline created using the Redpanda Cloud UI is allocated 0.1 vCPU and 400 MB of memory. This resource limit should let you experiment with pipelines that create low message vo
```suggestion
By default, every data pipeline created using the Redpanda Cloud UI is allocated 1.0 vCPU and 400 MB of memory. This resource limit should let you experiment with pipelines that create low message volumes of between 1-100 messages per second. 
```

Also do we want to publish the defaults in docs? If we change them we have to change the docs. 

> create low message volumes of between 1-100 messages per second.

Is this correct? This might be pipeline, payload, and workload dependant. How have we determined this range? Are we sure we want to publish numbers like this?

Both of these are really for @vladoschreiner Just wanted to double check.

2024-09-11 15:22 UTC, bojand commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +curl -X PUT "https://api.redpanda.com/v1alpha2/redpanda-connect/pipelines/<pipeline-id>"  \
Should `api.redpanda.com` be replaced with something that makes it explicit the user needs to use the data plane API URL, which is different for every Redpanda Cloud cluster.

2024-09-11 15:52 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +The following example allocates 3 vCPU and 500 MB of memory to data pipeline. The `memory_shares` parameter accepts a range of units. For example, `500M` (500 megabytes), `2G` (2 gigabytes), or `500M
@bojand - What do you think would be a more realistic resource allocation?

2024-09-11 15:52 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +curl -X PUT "https://api.redpanda.com/v1alpha2/redpanda-connect/pipelines/<pipeline-id>"  \
Yes, this is just a placeholder until I test.

2024-09-11 16:40 UTC, bojand commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +The following example allocates 3 vCPU and 500 MB of memory to data pipeline. The `memory_shares` parameter accepts a range of units. For example, `500M` (500 megabytes), `2G` (2 gigabytes), or `500M
We can just do `1.2` vCPU and `500M` for memory.

2024-09-12 10:10 UTC, vladoschreiner requested changes

2024-09-12 10:10 UTC, vladoschreiner commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +The following example allocates 3 vCPU and 500 MB of memory to data pipeline. The `memory_shares` parameter accepts a range of units. For example, `500M` (500 megabytes), `2G` (2 gigabytes), or `500M
Please explain the syntax. We can reduce it to number with a single decimal. No need to pitch the whole K8s syntax. 
E.g. CPU shares: 0.1 is a minimum. 
Memory: 0.4G, 2G. Nothing more granular

2024-09-13 00:49 UTC, bojand commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +The following example allocates 3 vCPU and 500 MB of memory to data pipeline. The `memory_shares` parameter accepts a range of units. For example, `500M` (500 megabytes), `2G` (2 gigabytes), or `500M
3 is fine. it's just an example. But people have a tendency to copy and paste so I just thought they would easily overprovision.

2024-09-13 15:13 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +By default, every data pipeline created using the Redpanda Cloud UI is allocated 0.1 vCPU and 400 MB of memory. This resource limit should let you experiment with pipelines that create low message vo
Updated.

2024-09-13 15:15 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +The following example allocates 3 vCPU and 500 MB of memory to data pipeline. The `memory_shares` parameter accepts a range of units. For example, `500M` (500 megabytes), `2G` (2 gigabytes), or `500M
Updated. I've tried to simplify as much as possible.

2024-09-13 15:15 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +To allocate more resources to a specific pipeline, you need to use the Data Plane API.
Updated.

2024-09-17 19:08 UTC, bojand commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +----
This should work now on new clusters.

```sh
❯ http -H "Authorization: Bearer $API_TOKEN" https://api-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines/crkt4rl8mchl4oiqcld0
HTTP/2 200
date: Tue, 17 Sep 2024 19:07:16 GMT
content-type: application/json
content-length: 902
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "id": "crkt4rl8mchl4oiqcld0",
    "display_name": "test0",
    "description": "",
    "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
    "resources": {
        "memory_shares": "400M",
        "cpu_shares": "1"
    },
    "state": "STATE_RUNNING"
}

~
❯ http PUT -H "Authorization: Bearer $API_TOKEN" https://api-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines/crkt4rl8mchl4oiqcld0 < ~/Downloads/putpipeline.json
HTTP/2 200
date: Tue, 17 Sep 2024 19:07:35 GMT
content-type: application/json
content-length: 904
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "id": "crkt4rl8mchl4oiqcld0",
    "display_name": "test0",
    "description": "",
    "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
    "resources": {
        "memory_shares": "500M",
        "cpu_shares": "1200m"
    },
    "state": "STATE_RUNNING"
}

~
❯ http -H "Authorization: Bearer $API_TOKEN" https://api-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com/v1alpha2/redpanda-connect/pipelines/crkt4rl8mchl4oiqcld0
HTTP/2 200
date: Tue, 17 Sep 2024 19:07:38 GMT
content-type: application/json
content-length: 904
grpc-metadata-content-type: application/grpc
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains

{
    "id": "crkt4rl8mchl4oiqcld0",
    "display_name": "test0",
    "description": "",
    "config_yaml": "input:\n  label: \"\"\n  generate:\n    mapping: root = {\"message\":\"pipeline\",\"id\":uuid_v4(),\"timestamp_ms\":timestamp_unix_micro(),\"timestamp\":now()}\n    interval: \"5s\"\n    count: 0\n    batch_size: 1\n    auto_replay_nacks: true\n\npipeline:\n  processors:\n    - bloblang: |\n        root = this\n        root.title = if root.message.type() == \"string\" {\n          root.message.uppercase()\n        }\n        \noutput:\n  label: \"rpconnect_gen_out\"\n  kafka_franz:\n    seed_brokers: [seed-703bb20a.crkruvcgrlev69gaig90.fmc.ign.cloud.redpanda.com:9092]\n    topic: \"rpconnect-gen-out\"\n    tls:\n      enabled: true\n    sasl:\n    - mechanism: SCRAM-SHA-256\n      password: rpconnect\n      username: rpconnect",
    "resources": {
        "memory_shares": "500M",
        "cpu_shares": "1200m"
    },
    "state": "STATE_RUNNING"
}
```

![image](https://github.com/user-attachments/assets/88c6167e-88bf-4bb6-bcad-90fb23a92a0d)

2024-09-17 19:09 UTC, bojand approved these changes

2024-09-23 08:33 UTC, vladoschreiner requested changes
I feel uncomfortable about the copy-paste experience.

Users aren't instructed to change the `config_yaml` content, making it prone to overriding the pipeline config with a demo content.

Shall we tell them to do GET first and only change the resource allocation?

2024-10-03 11:58 UTC, asimms41 commented
> I feel uncomfortable about the copy-paste experience.
> 
> Users aren't instructed to change the `config_yaml` content, making it prone to overriding the pipeline config with a demo content.
> 
> Shall we tell them to do GET first and only change the resource allocation?

@vladoschreiner. I've changed the workflow to include the GET request as suggested and I think I have made it more obvious that the example is just an example and is not intended for copy and paste.

2024-10-07 14:12 UTC, Feediver1 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +NOTE: If your resource request exceeds the maximum allowed limit, please contact Redpanda Support.
```suggestion
NOTE: If your resource request exceeds the maximum allowed limit, contact Redpanda Support.
```

2024-10-21 16:15 UTC, JakeSCahill commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +When you create a data pipeline through the Cloud UI, Redpanda Connect reserves compute resources for the exclusive use of that pipeline. This initial resource allocation should let you experiment wi
```suggestion
When you create a data pipeline through the Cloud UI, Redpanda Connect reserves compute resources for the exclusive use of that pipeline. This initial resource allocation is enough to experiment with pipelines that create low message volumes. 
```

2024-10-21 16:15 UTC, JakeSCahill commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +== Update Resources for a Data Pipeline
```suggestion
== Update resources for a data pipeline
```

2024-10-21 16:16 UTC, JakeSCahill commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> += Scaling Data Pipeline Resources on BYOC Clusters
```suggestion
= Scale Data Pipeline Resources on BYOC Clusters
```

2024-10-24 08:56 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> += Scaling Data Pipeline Resources on BYOC Clusters
Updated.

2024-10-24 08:57 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +== Update Resources for a Data Pipeline
Updated.

2024-10-24 09:06 UTC, asimms41 commented on modules/develop/pages/connect/configuration/scale-pipelines.adoc
> +When you create a data pipeline through the Cloud UI, Redpanda Connect reserves compute resources for the exclusive use of that pipeline. This initial resource allocation should let you experiment wi
Updated

2024-10-24 10:23 UTC, JakeSCahill approved these changes

2024-10-25 15:47 UTC, merged