add AWS pay as you go
redpanda-data/cloud-docs pull request #67
Opened 2024-09-14 01:22 UTC by micheleRP

## Description
This adds a page for pay-as-you-go billing on AWS.
This is an extension of https://github.com/redpanda-data/documentation-private/issues/2211

Review deadline: Wed Sept 18

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-09-14 01:26 UTC, micheleRP commented
@alenkacz can you please walk me through the purchase on AWS Marketplace. It looks a little different today from when we first wrote this page!

2024-09-17 05:08 UTC, alenkacz commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +. Review the purchase details, and click **Subscribe**. You're taken to the Redpanda sign-up page.
this is not true, they have to click on "set up on provider" or something like that. I think people miss that

2024-09-17 05:08 UTC, alenkacz commented on modules/get-started/pages/cloud-overview.adoc
> +To start using Dedicated, sign up for a free trial on the AWS Marketplace. New trials receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $30
what does this sentence mean?
```
You can also sign up direct for xref:billing:aws-pay-as-you-go.adoc[pay-as-you-go billing], without a trial, on AWS Marketplace.
```

2024-09-17 17:41 UTC, towfiqa commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +. Review the purchase details, and click **Subscribe**. You're taken to the Redpanda sign-up page.
They have to click "Setup your account" before the redpanda login page

2024-09-17 17:43 UTC, towfiqa commented on modules/billing/pages/aws-pay-as-you-go.adoc
>  Subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Redpanda Dedicated clusters. With a usage-based pay as you go subscription, you only pay for what you use and can cancel anyti
They will be able to provision Dedicated AND Serverless on AWS

2024-09-17 17:45 UTC, towfiqa commented on modules/get-started/pages/cloud-overview.adoc
> +To start using Dedicated, sign up for a free trial on the AWS Marketplace. New trials receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $30
I agree. I don't understand how they sign up direc on AWS Marketplace???

2024-09-17 17:49 UTC, towfiqa commented on modules/billing/pages/aws-pay-as-you-go.adoc
I think it would be good to add a "Tip" box here that says something like "if you are already a Redpanda customer, note that this process creates a new org which is separate from any other orgs you may have had before"

2024-09-17 17:52 UTC, towfiqa commented on modules/get-started/pages/cloud-overview.adoc
> +To start using Dedicated, sign up for a free trial on the AWS Marketplace. New trials receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $30
Replace "After 30 days," with "After your initial $300 is utilized"

2024-09-17 17:53 UTC, towfiqa requested changes
- Some inaccuracies found
- some user experience improvements suggested

2024-09-18 18:57 UTC, towfiqa commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +. In https://aws.amazon.com/marketplace[AWS Marketplace^], search for "redpanda", and select https://aws.amazon.com/marketplace/pp/prodview-ecbu7wwsfh644?applicationId=AWSMPContessa&ref_=beagle&sr=0-
Is there a reason we wouldn't just link them directly to the AWS Marketplace listing??? Why have the search at all?

2024-09-18 18:59 UTC, towfiqa commented on modules/get-started/pages/whats-new-cloud.adoc
> +To start using Dedicated, you can now sign up for a xref:get-started:cloud-overview.adoc#sign-up-for-dedicated[free trial on the AWS Marketplace]. New trials receive $300 (USD) in free credits to spe
This should be re-worded. They are not signing up for a trial. They are subscribing to Redpanda Cloud. But they get $300 to use for that subscription. The way this sentence is worded it sounds like they are subscribing to a trial, which is not the case. If they are on redpanda.com getting a serverless clusters, that's a trial.

2024-09-18 19:59 UTC, micheleRP commented on modules/billing/pages/aws-pay-as-you-go.adoc
> +. In https://aws.amazon.com/marketplace[AWS Marketplace^], search for "redpanda", and select https://aws.amazon.com/marketplace/pp/prodview-ecbu7wwsfh644?applicationId=AWSMPContessa&ref_=beagle&sr=0-
Yes, you're right. I've updated [here](http://localhost:5002/redpanda-cloud/billing/aws-pay-as-you-go/#sign-up-in-aws-marketplace)!

2024-09-19 03:46 UTC, towfiqa approved these changes

2024-09-19 16:04 UTC, JakeSCahill approved these changes
Minor suggestions

2024-09-19 16:04 UTC, JakeSCahill commented on modules/get-started/pages/cloud-overview.adoc
> +You can also subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] to quickly provision Serverless clusters. With a usage-based pay as you go subscription, you only
```suggestion
You can also subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] to quickly provision Serverless clusters. With a usage-based pay-as-you-go subscription, you only pay for what you use and can cancel anytime. 
```

2024-09-19 21:33 UTC, merged