DOC-670 Azure Marketplace Dedicated
redpanda-data/cloud-docs pull request #99
Opened 2024-10-25 01:55 UTC by micheleRP

## Description

Resolves https://redpandadata.atlassian.net/browse/DOC-670
Review deadline:

## Page previews

## Checks

- [X] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-10-28 22:44 UTC, kbatuigas requested changes
Just a couple of clarifying questions. I don't know if any of these are actually blockers so I will request changes, just in case.

2024-10-28 22:44 UTC, kbatuigas commented on modules/billing/pages/azure-commit.adoc
> +When you subscribe to Redpanda Cloud through Azure Marketplace, you can only create clusters on AWS.
Just want to double check if we also meant to say "Azure" instead of "AWS" here?

2024-10-28 22:44 UTC, kbatuigas commented on modules/billing/pages/azure-commit.adoc
Just want to double check that we mean to use the shortened term "commit" with the nav links only. Looks like each provider has their own terminology for these billing programs but they at least seem to mention or share usage of "commitment" -- do we want to consider updating the nav links so they match the page titles? Or mention "commit" in the doc itself? I'm assuming that's used informally when talking to customers?

2024-10-28 22:44 UTC, kbatuigas commented on modules/billing/pages/azure-commit.adoc
> +When you subscribe to Redpanda Cloud through Azure Marketplace, you can only create clusters on AWS.
Also, does this mean "you can only deploy AWS clusters, if you also want to use other providers with RP Cloud you can have separate org subscriptions to those providers"?

2024-10-28 22:54 UTC, micheleRP commented on modules/billing/pages/azure-commit.adoc
> +When you subscribe to Redpanda Cloud through Azure Marketplace, you can only create clusters on AWS.
good catch, thanks!

2024-10-28 23:05 UTC, micheleRP commented on modules/billing/pages/azure-commit.adoc
> +When you subscribe to Redpanda Cloud through Azure Marketplace, you can only create clusters on AWS.
Yeah, that AWS is a typo (fixed), but when you subscribe through Azure marketplace and log in to that org in Redpanda Cloud, the create cluster page defaults to Azure, with other providers grayed out.

2024-10-28 23:41 UTC, kbatuigas approved these changes
Just one more clarifying comment, but lgtm otherwise.

2024-10-28 23:41 UTC, kbatuigas commented on modules/get-started/pages/cloud-overview.adoc
> +Alternatively, you can contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer for monthly or annual committed use. With a usage-based billing c
I think the last sentence makes it sound like users can provision RP clusters in the marketplace UI (i.e. outside of the Cloud UI) - if that's the case this sounds good to me, but if not I think we could rephrase a bit.

2024-10-29 01:09 UTC, micheleRP commented on modules/get-started/pages/cloud-overview.adoc
> +Alternatively, you can contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer for monthly or annual committed use. With a usage-based billing c
thanks, Kat: no, we don't want users to think you provision clusters in marketplace! I've clarified the docs!

2024-10-29 01:09 UTC, micheleRP commented on modules/billing/pages/azure-commit.adoc
resolved in slack

2024-10-29 07:19 UTC, alenkacz reviewed
LGTM, left just small comments

2024-10-29 07:19 UTC, alenkacz commented on modules/billing/pages/azure-commit.adoc
> +If you don't have a billing account associated with your project, you're prompted to enable billing to link the subscription with a billing account.
nit: I don't think this is correct language with Azure, there's no project and not sure it's called billing account. We should ask @ncole to review these wording

2024-10-29 07:19 UTC, alenkacz commented on modules/billing/pages/azure-commit.adoc
> +* For **Organization name**, enter a name for your new organization connected through Azure Marketplace. Redpanda organizations contain all resources, including clusters and networks.
for existing cloud users, we have to manually associate their existing account with marketplace. We're planning to add this to the UI but it is currently being prioritized. I'll circle back to docs if prioritized as it will require changes in docs

2024-10-29 16:07 UTC, micheleRP commented on modules/billing/pages/azure-commit.adoc
> +If you don't have a billing account associated with your project, you're prompted to enable billing to link the subscription with a billing account.
@alenkacz, @ncole: Please review this updated wording: https://deploy-preview-99--rp-cloud.netlify.app/redpanda-cloud/billing/azure-commit/#sign-up-in-azure-marketplace

2024-10-30 14:36 UTC, merged